/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as RoadmapRouteImport } from './routes/roadmap'
import { Route as SigninRouteImport } from './routes/signin'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as DashboardAiInterviewRouteImport } from './routes/dashboard.ai-interview'
import { Route as DashboardCareerAnalysisRouteImport } from './routes/dashboard.career-analysis'
import { Route as DashboardResumeAnalyzerRouteImport } from './routes/dashboard.resume-analyzer'
import { Route as DashboardSettingsRouteImport } from './routes/dashboard.settings'
import { Route as DashboardSkillGapRouteImport } from './routes/dashboard.skill-gap'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const RoadmapRoute = RoadmapRouteImport.update({
  id: '/roadmap',
  path: '/roadmap',
  getParentRoute: () => rootRouteImport,
} as any)
const SigninRoute = SigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardAiInterviewRoute = DashboardAiInterviewRouteImport.update({
  id: '/dashboard/ai-interview',
  path: '/dashboard/ai-interview',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardCareerAnalysisRoute = DashboardCareerAnalysisRouteImport.update({
  id: '/dashboard/career-analysis',
  path: '/dashboard/career-analysis',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardResumeAnalyzerRoute = DashboardResumeAnalyzerRouteImport.update({
  id: '/dashboard/resume-analyzer',
  path: '/dashboard/resume-analyzer',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/dashboard/settings',
  path: '/dashboard/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardSkillGapRoute = DashboardSkillGapRouteImport.update({
  id: '/dashboard/skill-gap',
  path: '/dashboard/skill-gap',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/profile': typeof ProfileRoute
  '/roadmap': typeof RoadmapRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/dashboard/ai-interview': typeof DashboardAiInterviewRoute
  '/dashboard/career-analysis': typeof DashboardCareerAnalysisRoute
  '/dashboard/resume-analyzer': typeof DashboardResumeAnalyzerRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/skill-gap': typeof DashboardSkillGapRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/profile': typeof ProfileRoute
  '/roadmap': typeof RoadmapRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/dashboard/ai-interview': typeof DashboardAiInterviewRoute
  '/dashboard/career-analysis': typeof DashboardCareerAnalysisRoute
  '/dashboard/resume-analyzer': typeof DashboardResumeAnalyzerRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/skill-gap': typeof DashboardSkillGapRoute
  '/dashboard': typeof DashboardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/profile': typeof ProfileRoute
  '/roadmap': typeof RoadmapRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/dashboard/ai-interview': typeof DashboardAiInterviewRoute
  '/dashboard/career-analysis': typeof DashboardCareerAnalysisRoute
  '/dashboard/resume-analyzer': typeof DashboardResumeAnalyzerRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/skill-gap': typeof DashboardSkillGapRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/profile'
    | '/roadmap'
    | '/signin'
    | '/signup'
    | '/dashboard/ai-interview'
    | '/dashboard/career-analysis'
    | '/dashboard/resume-analyzer'
    | '/dashboard/settings'
    | '/dashboard/skill-gap'
    | '/dashboard/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/profile'
    | '/roadmap'
    | '/signin'
    | '/signup'
    | '/dashboard/ai-interview'
    | '/dashboard/career-analysis'
    | '/dashboard/resume-analyzer'
    | '/dashboard/settings'
    | '/dashboard/skill-gap'
    | '/dashboard'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/profile'
    | '/roadmap'
    | '/signin'
    | '/signup'
    | '/dashboard/ai-interview'
    | '/dashboard/career-analysis'
    | '/dashboard/resume-analyzer'
    | '/dashboard/settings'
    | '/dashboard/skill-gap'
    | '/dashboard/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  ProfileRoute: typeof ProfileRoute
  RoadmapRoute: typeof RoadmapRoute
  SigninRoute: typeof SigninRoute
  SignupRoute: typeof SignupRoute
  DashboardAiInterviewRoute: typeof DashboardAiInterviewRoute
  DashboardCareerAnalysisRoute: typeof DashboardCareerAnalysisRoute
  DashboardResumeAnalyzerRoute: typeof DashboardResumeAnalyzerRoute
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DashboardSkillGapRoute: typeof DashboardSkillGapRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roadmap': {
      id: '/roadmap'
      path: '/roadmap'
      fullPath: '/roadmap'
      preLoaderRoute: typeof RoadmapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signin': {
      id: '/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof SigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/ai-interview': {
      id: '/dashboard/ai-interview'
      path: '/dashboard/ai-interview'
      fullPath: '/dashboard/ai-interview'
      preLoaderRoute: typeof DashboardAiInterviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/career-analysis': {
      id: '/dashboard/career-analysis'
      path: '/dashboard/career-analysis'
      fullPath: '/dashboard/career-analysis'
      preLoaderRoute: typeof DashboardCareerAnalysisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/resume-analyzer': {
      id: '/dashboard/resume-analyzer'
      path: '/dashboard/resume-analyzer'
      fullPath: '/dashboard/resume-analyzer'
      preLoaderRoute: typeof DashboardResumeAnalyzerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/dashboard/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/skill-gap': {
      id: '/dashboard/skill-gap'
      path: '/dashboard/skill-gap'
      fullPath: '/dashboard/skill-gap'
      preLoaderRoute: typeof DashboardSkillGapRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  ProfileRoute: ProfileRoute,
  RoadmapRoute: RoadmapRoute,
  SigninRoute: SigninRoute,
  SignupRoute: SignupRoute,
  DashboardAiInterviewRoute: DashboardAiInterviewRoute,
  DashboardCareerAnalysisRoute: DashboardCareerAnalysisRoute,
  DashboardResumeAnalyzerRoute: DashboardResumeAnalyzerRoute,
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardSkillGapRoute: DashboardSkillGapRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
